site_name: Loop Tips
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- Home: 'index.md'
- Settings:
    - 'Why Settings Matter': 'settings/overview.md'
    - 'Initial Settings': 'settings/settings.md'
    - 'Adjust Your Settings': 'settings/adjust.md'
- Data Tools:
    - 'Overview': 'data/overview.md'
    - 'Health': 'data/health.md'
    - 'Nightscout': 'data/nightscout.md'
    - 'Tidepool': 'data/tidepool.md'
    - 'Perceptus': 'data/glucodyn.md'
- How To:
    - 'CGM habits': 'how-to/cgm.md'
    - 'Use morning IOB': 'how-to/iob.md'
    - 'Override Targets': 'how-to/overrides.md'
    - 'Low Treatments': 'how-to/low-treat.md'
    - 'Shower & Swimming': 'how-to/disconnect.md'
    - 'Exercise': 'how-to/exercise.md'
    - 'Extended Bolus': 'how-to/bolus.md'
    - 'Site Failure': 'how-to/site-fail.md'
    - 'Stuck on High': 'how-to/high-bg.md'
    - 'Talk with Endo': 'how-to/endo.md'
- Algorithm:
    - 'Overview': 'algorithm/overview.md'
    - 'Prediction': 'algorithm/prediction.md'
    - 'Basal': 'algorithm/temp-basal.md'
    - 'Bolus': 'algorithm/bolus.md'

