site_name: GitHub Docs
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- 'index.md'
- GitHub:
    - 'Overview': 'github/overview.md'
    - 'Repos and Branches': 'github/repos.md'
    - 'Commits': 'github/commit.md'
    - 'Compare, PR, Merge': 'github/compare.md'
    - 'Start Over': 'github/delete.md'
    - 'Git commands': 'github/local.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Updating Site': 'nightscout/updating.md'
    - 'Loop Users': 'nightscout/loop.md'
    - 'OpenAPS Users': 'nightscout/openaps.md'
- Loop:
    - 'Overview': 'loop/overview.md'
    - 'Loop source code': 'loop/loop_source.md'
    - 'Loop docs': 'loop/loop_docs.md'
- OpenAPS:
    - 'Overview': 'openaps/overview.md'
    - 'Docs': 'openaps/openaps_docs.md'
    - 'oref0': 'openaps/oref0.md'    
